### ISSUE TITLE
YAML for configuration rather than config.js

### ISSUE THREAD

**Issue by robogeek** [akashacms/akasharender#8]
It might be better to configure using YAML rather than a JS file.

The methodology would be 

- The first level is an Object - and the configFromYAML steps through the fields of the Object
- The fields are defined and each field handled by its own code section

Plugins would be configured something like

```
    plugins:
         - use: "plugin-reference"
            configSetting: "config Value"
            configSetting: "config Value"
         - use: "plugin-reference"
            configSetting: "config Value"
            configSetting: "config Value"
```

Stylesheets

```
     stylesheets:
             - href: "/vendor/jquery/..."
             - href: "/vendor/bootstrap/..."
    javaScriptTop:
            - href: "/vendor/jquery/..."
            - href: "/vendor/bootstrap/..."
    javaScriptBottom:
            - href: "/vendor/jquery/..."
            - href: "/vendor/bootstrap/..."
```
